name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Assemble agent
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew shadowJar -Pversion=${{ github.event.release.name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.release.name }}
          draft: true
          files: |
            build/libs/*.jar

#      - name: Assemble and publish
#        env:
#          GITHUB_ACTOR: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: ./gradlew publish -Pversion=${{ github.event.release.name }}

